# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import subprocess

from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow, commit_dialog, repo_path):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_list = QtWidgets.QListView(self.centralwidget)
        self.file_list.setGeometry(QtCore.QRect(10, 20, 121, 721))
        self.file_list.setObjectName("file_list")
        # self.commit_tree = QtWidgets.QTreeWidget(self.centralwidget)
        # self.commit_tree.setGeometry(QtCore.QRect(140, 20, 641, 721))
        # self.commit_tree.setObjectName("commit_tree")
        # self.commit_tree.headerItem().setText(0, "1")
        self.commit_info = QtWidgets.QTextEdit(self.centralwidget)
        self.commit_info.setGeometry(QtCore.QRect(790, 20, 201, 201))
        self.commit_info.setObjectName("commit_info")
        self.commit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.commit_btn.setGeometry(QtCore.QRect(790, 690, 201, 51))
        self.commit_btn.setObjectName("commit_btn")
        self.checkout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.checkout_btn.setGeometry(QtCore.QRect(790, 260, 201, 51))
        self.checkout_btn.setObjectName("checkout_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.commit_dialog = commit_dialog
        self.checkout_btn.clicked.connect(self.checkout_dialog)
        
        self.repo_path = repo_path

        self.commit_btn.clicked.connect(self.create_commit_dialog)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.commit_btn.setText(_translate("MainWindow", "Commit"))
        self.checkout_btn.setText(_translate("MainWindow", "Checkout"))
    
    def checkout_dialog(self):
        tonq = QtWidgets.QMessageBox()
        tonq.setText('Do you really want checkout to this commit?')
        tonq.setIcon(QtWidgets.QMessageBox.Warning)
        tonq.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.Cancel)
        tonq.buttonClicked.connect(self.checkout_btn_click)
        tonq.exec_()
        #  self.checkout_dialog.exec_()
    
    def create_commit_dialog(self):
        self.commit_dialog.show()

    
    def checkout_btn_click(self, btn):
        if btn.text() == 'OK':
            # некоторая логика, которая в cmd даёт команду на checkout
            return None



class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, commit_dialog, repo_path=''):
        super().__init__()
        self.setupUi(self, commit_dialog, repo_path)
    
    def rerender(self):
        self.setWindowTitle(self.repo_path)



if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ex = MainWindow()
    ex.show()
    sys.exit(app.exec_())

